from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

from multivari.common.io import read_table
from multivari.common.schema import HIVE_COLUMN, TIMESTAMP_COLUMN

from .config import AbscondingSettings
from .events import evaluate_event_warnings
from .metrics import choose_alert_threshold, classification_metrics, selection_score
from .pipeline import AbscondingPaths, prepare_absconding_dataset


@dataclass(frozen=True)
class SequenceSet:
    X: np.ndarray
    y: np.ndarray
    metadata: pd.DataFrame


@dataclass(frozen=True)
class LstmTrainingOptions:
    sequence_length: int = 72
    stride: int = 3
    epochs: int = 30
    batch_size: int = 256
    patience: int = 5
    maximum_train_sequences: int = 30_000
    maximum_validation_sequences: int = 15_000
    maximum_test_sequences: int = 15_000
    maximum_positive_class_weight: float = 50.0
    learning_rate: float = 0.001


def preferred_lstm_features(all_features: list[str]) -> list[str]:
    """Select a compact, report-aligned feature set for sequence learning.

    Keeping the LSTM feature set compact prevents multi-gigabyte sequence arrays while
    retaining raw sensors, temporal context, changes, rolling behaviour and stress features.
    """
    exact = {
        "temperature_c",
        "humidity_pct",
        "co2_ppm",
        "weight_kg",
        "hour_sin",
        "hour_cos",
        "day_of_year_sin",
        "day_of_year_cos",
        "temperature_deviation_from_35",
        "humidity_deviation_from_optimal",
        "co2_high_flag",
        "rapid_weight_loss_flag",
        "sustained_weight_loss_24h",
        "sustained_weight_loss_72h",
        "environmental_stress_score",
        "stress_trend_24h",
        "multisensor_instability_index",
        "temperature_humidity_interaction",
        "weight_decline_fraction_24h",
        "weight_decline_fraction_72h",
        "co2_rise_fraction_24h",
        "co2_rise_fraction_72h",
    }
    suffixes = (
        "_change_1h",
        "_change_6h",
        "_change_24h",
        "_change_72h",
        "_roll_mean_6h",
        "_roll_mean_24h",
        "_roll_mean_72h",
        "_roll_std_6h",
        "_roll_std_24h",
        "_roll_std_72h",
    )
    selected = [
        feature
        for feature in all_features
        if feature in exact or feature.endswith(suffixes)
    ]
    # Preserve the feature order generated by the common pipeline.
    return list(dict.fromkeys(selected))


def train_absconding_lstm(
    *,
    backend_root: str | Path,
    config_path: str | Path | None = None,
    options: LstmTrainingOptions | None = None,
) -> dict[str, Any]:
    """Train, evaluate and persist a real LSTM sequence comparison model."""
    options = options or LstmTrainingOptions()
    paths = AbscondingPaths(Path(backend_root).resolve())
    settings = AbscondingSettings.from_yaml(config_path or paths.config)
    paths.create_output_directories()

    tensorflow, keras = _import_tensorflow()
    tensorflow.keras.utils.set_random_seed(settings.random_state)

    clean = read_table(paths.clean_data)
    manifest = read_table(paths.split_manifest)
    clean[TIMESTAMP_COLUMN] = pd.to_datetime(clean[TIMESTAMP_COLUMN], errors="raise")
    manifest[TIMESTAMP_COLUMN] = pd.to_datetime(manifest[TIMESTAMP_COLUMN], errors="raise")

    prepared, all_features, episodes = prepare_absconding_dataset(clean, manifest, settings)
    feature_names = preferred_lstm_features(all_features)
    if not feature_names:
        raise RuntimeError("No LSTM features were selected from the prepared dataset.")

    train_rows = prepared.loc[prepared["split"].eq("train")]
    imputer = SimpleImputer(strategy="median")
    scaler = StandardScaler()
    train_imputed = imputer.fit_transform(train_rows[feature_names])
    scaler.fit(train_imputed)

    sets = {}
    maximum_by_split = {
        "train": options.maximum_train_sequences,
        "validation": options.maximum_validation_sequences,
        "test": options.maximum_test_sequences,
    }
    for split in ("train", "validation", "test"):
        split_frame = prepared.loc[prepared["split"].eq(split)].copy()
        sets[split] = build_sequence_set(
            split_frame,
            feature_names=feature_names,
            target_column=settings.target_column,
            sequence_length=options.sequence_length,
            stride=options.stride,
            imputer=imputer,
            scaler=scaler,
            maximum_sequences=maximum_by_split[split],
            random_state=settings.random_state,
        )

    _validate_sequence_classes(sets)
    X_train, y_train = sets["train"].X, sets["train"].y
    X_validation, y_validation = sets["validation"].X, sets["validation"].y
    X_test, y_test = sets["test"].X, sets["test"].y

    positive_count = int(y_train.sum())
    negative_count = int(len(y_train) - positive_count)
    positive_weight = min(
        options.maximum_positive_class_weight,
        negative_count / max(positive_count, 1),
    )
    class_weight = {0: 1.0, 1: float(max(1.0, positive_weight))}

    model = keras.Sequential(
        [
            keras.layers.Input(shape=(options.sequence_length, len(feature_names))),
            keras.layers.LSTM(128, return_sequences=True),
            keras.layers.Dropout(0.30),
            keras.layers.LSTM(64),
            keras.layers.Dropout(0.25),
            keras.layers.Dense(32, activation="relu"),
            keras.layers.Dense(1, activation="sigmoid"),
        ],
        name="absconding_lstm_sequence",
    )
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=options.learning_rate),
        loss="binary_crossentropy",
        metrics=[
            keras.metrics.Precision(name="precision"),
            keras.metrics.Recall(name="recall"),
            keras.metrics.AUC(name="roc_auc"),
            keras.metrics.AUC(name="pr_auc", curve="PR"),
        ],
    )

    model_path = paths.model_directory / "absconding_lstm_sequence.keras"
    history_path = paths.metrics_directory / "lstm_training_history.csv"
    callbacks = [
        keras.callbacks.ModelCheckpoint(
            filepath=model_path,
            monitor="val_pr_auc",
            mode="max",
            save_best_only=True,
        ),
        keras.callbacks.EarlyStopping(
            monitor="val_pr_auc",
            mode="max",
            patience=options.patience,
            restore_best_weights=True,
        ),
        keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            mode="min",
            factor=0.5,
            patience=max(2, options.patience // 2),
            min_lr=1e-5,
        ),
        keras.callbacks.CSVLogger(history_path),
    ]

    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_validation, y_validation),
        epochs=options.epochs,
        batch_size=options.batch_size,
        class_weight=class_weight,
        callbacks=callbacks,
        shuffle=True,
        verbose=1,
    )

    # Reload the best checkpoint so saved and evaluated weights are identical.
    model = keras.models.load_model(model_path)
    validation_probability = model.predict(
        X_validation, batch_size=options.batch_size, verbose=0
    ).reshape(-1)
    threshold_selection = choose_alert_threshold(
        y_validation,
        validation_probability,
        beta=settings.threshold_beta,
        maximum_alert_fraction=settings.maximum_validation_alert_fraction,
    )
    threshold = float(threshold_selection["threshold"])
    validation_metrics = classification_metrics(
        y_validation, validation_probability, threshold
    )
    validation_frame = _sequence_prediction_frame(
        sets["validation"], validation_probability, settings.target_column
    )
    validation_event_metrics, validation_event_details = evaluate_event_warnings(
        validation_frame,
        episodes,
        threshold=threshold,
        horizon_hours=settings.prediction_horizon_hours,
        split="validation",
    )

    test_probability = model.predict(
        X_test, batch_size=options.batch_size, verbose=0
    ).reshape(-1)
    test_metrics = classification_metrics(y_test, test_probability, threshold)
    test_frame = _sequence_prediction_frame(
        sets["test"], test_probability, settings.target_column
    )
    test_event_metrics, test_event_details = evaluate_event_warnings(
        test_frame,
        episodes,
        threshold=threshold,
        horizon_hours=settings.prediction_horizon_hours,
        split="test",
    )

    score = selection_score(validation_metrics, validation_event_metrics)
    if not threshold_selection["constraint_satisfied"]:
        alert_fraction = max(float(threshold_selection["alert_fraction"]), 1e-12)
        score *= min(1.0, settings.maximum_validation_alert_fraction / alert_fraction)

    preprocessor_path = paths.model_directory / "absconding_lstm_preprocessor.joblib"
    joblib.dump(
        {
            "imputer": imputer,
            "scaler": scaler,
            "feature_names": feature_names,
            "sequence_length": options.sequence_length,
            "stride": options.stride,
            "target_column": settings.target_column,
            "settings": settings.to_dict(),
        },
        preprocessor_path,
    )

    result = {
        "model_key": "lstm_sequence",
        "model_name": "LSTM + Time-Series Sequence",
        "model_family": "Deep learning sequence model",
        "status": "completed",
        "selection_score": round(float(score), 8),
        "threshold_selection": _json_ready(threshold_selection),
        "validation_metrics": validation_metrics,
        "validation_event_metrics": validation_event_metrics,
        "test_metrics": test_metrics,
        "test_event_metrics": test_event_metrics,
        "comparison_training_records": len(X_train),
        "validation_sequences": len(X_validation),
        "test_sequences": len(X_test),
        "training_positive_sequences": int(y_train.sum()),
        "validation_positive_sequences": int(y_validation.sum()),
        "test_positive_sequences": int(y_test.sum()),
        "sequence_length": options.sequence_length,
        "stride": options.stride,
        "feature_count": len(feature_names),
        "target_column": settings.target_column,
        "prediction_horizon_hours": settings.prediction_horizon_hours,
        "features_used": feature_names,
        "epochs_requested": options.epochs,
        "epochs_completed": len(history.history.get("loss", [])),
        "batch_size": options.batch_size,
        "positive_class_weight": round(float(class_weight[1]), 6),
        "model_path": str(model_path.relative_to(paths.backend_root)),
        "preprocessor_path": str(preprocessor_path.relative_to(paths.backend_root)),
        "deployment_status": "comparison_only",
        "deployment_note": (
            "The current live IoT endpoint continues using the validation-selected tabular model. "
            "Promote LSTM to live inference only after it is clearly superior and more labelled "
            "absconding episodes are available."
        ),
    }

    result_path = paths.metrics_directory / "lstm_comparison.json"
    result_path.write_text(json.dumps(_json_ready(result), indent=2), encoding="utf-8")
    pd.DataFrame(validation_event_details).to_csv(
        paths.metrics_directory / "lstm_validation_event_detection.csv", index=False
    )
    pd.DataFrame(test_event_details).to_csv(
        paths.metrics_directory / "lstm_test_event_detection.csv", index=False
    )
    _merge_result_into_existing_outputs(paths, result)
    return result


def build_sequence_set(
    frame: pd.DataFrame,
    *,
    feature_names: list[str],
    target_column: str,
    sequence_length: int,
    stride: int,
    imputer: SimpleImputer,
    scaler: StandardScaler,
    maximum_sequences: int,
    random_state: int,
) -> SequenceSet:
    """Create event-preserving windows without materialising every possible window."""
    group_values: list[np.ndarray] = []
    descriptors: list[tuple[int, int, int, str, pd.Timestamp, str]] = []

    for hive_id, group in frame.groupby(HIVE_COLUMN, sort=False):
        group = group.sort_values(TIMESTAMP_COLUMN).reset_index(drop=True)
        if len(group) < sequence_length:
            continue
        transformed = scaler.transform(imputer.transform(group[feature_names])).astype(
            "float32"
        )
        group_index = len(group_values)
        group_values.append(transformed)
        targets = group[target_column].to_numpy(dtype="int8")
        positive_endpoints = np.flatnonzero(targets == 1)
        positive_endpoints = positive_endpoints[positive_endpoints >= sequence_length - 1]
        regular_endpoints = np.arange(sequence_length - 1, len(group), max(stride, 1))
        endpoints = np.unique(np.concatenate([positive_endpoints, regular_endpoints]))
        for endpoint in endpoints:
            descriptors.append(
                (
                    group_index,
                    int(endpoint),
                    int(targets[endpoint]),
                    str(hive_id),
                    pd.Timestamp(group.loc[endpoint, TIMESTAMP_COLUMN]),
                    str(group.loc[endpoint, "split"]),
                )
            )

    if not descriptors:
        return SequenceSet(
            X=np.empty((0, sequence_length, len(feature_names)), dtype="float32"),
            y=np.empty((0,), dtype="int8"),
            metadata=pd.DataFrame(columns=[HIVE_COLUMN, TIMESTAMP_COLUMN, "split"]),
        )

    all_labels = np.asarray([item[2] for item in descriptors], dtype="int8")
    selected = _event_preserving_positions(
        all_labels,
        maximum_sequences=maximum_sequences,
        random_state=random_state,
    )
    X = np.empty(
        (len(selected), sequence_length, len(feature_names)), dtype="float32"
    )
    y = np.empty((len(selected),), dtype="int8")
    metadata_rows: list[dict[str, Any]] = []
    for output_index, descriptor_position in enumerate(selected):
        group_index, endpoint, label, hive_id, timestamp, split = descriptors[
            descriptor_position
        ]
        start = endpoint - sequence_length + 1
        X[output_index] = group_values[group_index][start : endpoint + 1]
        y[output_index] = label
        metadata_rows.append(
            {
                HIVE_COLUMN: hive_id,
                TIMESTAMP_COLUMN: timestamp,
                "split": split,
            }
        )
    return SequenceSet(X=X, y=y, metadata=pd.DataFrame(metadata_rows))

def _event_preserving_positions(
    y: np.ndarray,
    *,
    maximum_sequences: int,
    random_state: int,
) -> np.ndarray:
    all_positions = np.arange(len(y))
    if maximum_sequences <= 0 or len(y) <= maximum_sequences:
        return all_positions
    positives = all_positions[y == 1]
    negatives = all_positions[y == 0]
    negative_limit = max(maximum_sequences - len(positives), 0)
    if negative_limit >= len(negatives):
        selected_negatives = negatives
    elif negative_limit == 0:
        selected_negatives = np.empty((0,), dtype=int)
    else:
        rng = np.random.default_rng(random_state)
        selected_negatives = np.sort(
            rng.choice(negatives, size=negative_limit, replace=False)
        )
    return np.sort(np.concatenate([positives, selected_negatives]))


def _sequence_prediction_frame(
    sequence_set: SequenceSet,
    probability: np.ndarray,
    target_column: str,
) -> pd.DataFrame:
    result = sequence_set.metadata.copy()
    result[target_column] = sequence_set.y
    result["absconding_probability"] = probability
    return result


def _validate_sequence_classes(sets: dict[str, SequenceSet]) -> None:
    for split, sequence_set in sets.items():
        if len(sequence_set.y) == 0:
            raise ValueError(
                f"No {split} LSTM sequences were created. Reduce the sequence length or check the split."
            )
        classes = np.unique(sequence_set.y)
        if len(classes) < 2:
            raise ValueError(
                f"The {split} LSTM sequence set contains only class {classes.tolist()}. "
                "More labelled absconding events are required for a defensible sequence comparison."
            )


def _merge_result_into_existing_outputs(
    paths: AbscondingPaths,
    result: dict[str, Any],
) -> None:
    comparison_path = paths.metrics_directory / "model_comparison.json"
    if comparison_path.is_file():
        comparison = json.loads(comparison_path.read_text(encoding="utf-8"))
        comparison = [
            row for row in comparison if row.get("model_key") != result["model_key"]
        ]
        comparison.append(result)
        comparison.sort(key=lambda row: row.get("selection_score", -1.0), reverse=True)
        comparison_path.write_text(
            json.dumps(_json_ready(comparison), indent=2), encoding="utf-8"
        )
        pd.json_normalize(comparison).to_csv(
            paths.metrics_directory / "model_comparison.csv", index=False
        )

    dashboard_path = paths.report_directory / "absconding_dashboard.json"
    if not dashboard_path.is_file():
        return
    dashboard = json.loads(dashboard_path.read_text(encoding="utf-8"))
    detailed = dashboard.get("model_training", {}).get("model_comparison", [])
    detailed = [row for row in detailed if row.get("model_key") != result["model_key"]]
    detailed.append(result)
    detailed.sort(key=lambda row: row.get("selection_score", -1.0), reverse=True)
    dashboard.setdefault("model_training", {})["model_comparison"] = detailed
    dashboard["model_training"]["lstm"] = result

    legacy = dashboard.get("model_comparison", [])
    legacy = [row for row in legacy if row.get("model_key") != result["model_key"]]
    legacy_row = {
        "model_key": result["model_key"],
        "model_name": result["model_name"],
        "model_family": result["model_family"],
        "accuracy": result["validation_metrics"].get("accuracy"),
        "precision": result["validation_metrics"].get("precision"),
        "recall": result["validation_metrics"].get("recall"),
        "f1_score": result["validation_metrics"].get("f1_score"),
        "pr_auc": result["validation_metrics"].get("pr_auc"),
        "roc_auc": result["validation_metrics"].get("roc_auc"),
        "mae": result["validation_metrics"].get("mae"),
        "rmse": result["validation_metrics"].get("rmse"),
        "defence_score": result["selection_score"],
        "event_recall": result["validation_event_metrics"].get("event_recall"),
        "threshold": result["threshold_selection"].get("threshold"),
        "status": result["status"],
        "error": None,
    }
    legacy.append(legacy_row)
    legacy.sort(key=lambda row: row.get("defence_score", -1.0), reverse=True)
    dashboard["model_comparison"] = legacy

    rationale = dashboard.setdefault("model_selection_rationale", {})
    rationale["lstm_metrics_available"] = True
    rationale["is_lstm_best"] = bool(
        legacy and legacy[0].get("model_key") == result["model_key"]
    )
    if legacy:
        rationale["best_model_by_defence_score"] = legacy[0].get("model_name")
    rationale["lstm_deployment_status"] = result["deployment_status"]
    rationale["lstm_deployment_note"] = result["deployment_note"]
    dashboard_path.write_text(
        json.dumps(_json_ready(dashboard), indent=2), encoding="utf-8"
    )


def _import_tensorflow():
    try:
        import tensorflow as tf
        from tensorflow import keras
    except ImportError as error:
        raise RuntimeError(
            'TensorFlow is required. Install the optional dependency with: '
            'python -m pip install -e ".[dev,lstm]"'
        ) from error
    return tf, keras


def _json_ready(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _json_ready(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_json_ready(item) for item in value]
    if isinstance(value, tuple):
        return [_json_ready(item) for item in value]
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return None if not np.isfinite(value) else float(value)
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    return value
