import {
  BarChart3,
  CalendarDays,
  Clock3,
  Database,
  Images,
  ShieldCheck,
  Users,
} from 'lucide-react';
import { Panel } from '../../components/common/Panel';
import { StatCard } from '../../components/common/StatCard';
import { CorrelationHeatmap } from './CorrelationHeatmap';
import { DataQualityChart } from './DataQualityChart';
import { HiveCoverageChart } from './HiveCoverageChart';
import { HourlyPatternsChart } from './HourlyPatternsChart';
import { MonthlyPatternsChart } from './MonthlyPatternsChart';
import { OutlierAnalysisChart } from './OutlierAnalysisChart';
import { ReportFiguresGallery } from './ReportFiguresGallery';
import { SensorDistributionChart } from './SensorDistributionChart';
import { SensorRelationshipChart } from './SensorRelationshipChart';
import { SensorStatisticsTable } from './SensorStatisticsTable';
import { TargetBalanceChart } from './TargetBalanceChart';
import { TargetByHiveChart } from './TargetByHiveChart';
import { TargetCooccurrenceHeatmap } from './TargetCooccurrenceHeatmap';
import { TargetPositiveRateChart } from './TargetPositiveRateChart';
import { TargetSensorEffectChart } from './TargetSensorEffectChart';
import { TargetTimelineChart } from './TargetTimelineChart';
import { WeekdayPatternsChart } from './WeekdayPatternsChart';

function dateOnly(value) {
  return value ? String(value).slice(0, 10) : '—';
}

export function CommonEDAPage({ edaData }) {
  const summary = edaData?.summary || {};
  const quality = edaData?.data_quality || {};

  return (
    <div className="page-stack">
      <div className="page-heading eda-heading">
        <div>
          <span className="eyebrow">COMMON DATA LAYER</span>
          <h2>Exploratory data analysis</h2>
        </div>
        <div className="dataset-period">
          <CalendarDays size={18} />
          <span>{dateOnly(summary.analysis_start)} to {dateOnly(summary.analysis_end)}</span>
        </div>
      </div>

      <div className="stats-grid stats-grid-six">
        <StatCard label="Records" value={summary.total_records} icon={Database} note="Cleaned common observations" />
        <StatCard label="Hives" value={summary.total_hives} icon={Users} note="Independent chronological streams" />
        <StatCard label="Observed period" value={summary.duration_days} unit="days" icon={CalendarDays} />
        <StatCard label="Sampling interval" value={summary.sampling_frequency} icon={Clock3} />
        <StatCard label="Missing values" value={quality.missing_values ?? 0} icon={ShieldCheck} />
        <StatCard label="Duplicate timestamps" value={quality.duplicate_timestamps ?? 0} icon={BarChart3} />
      </div>

      <Panel
        title="Generated report figures — exact output"
        action={<Images size={20} />}
      >
        <ReportFiguresGallery images={edaData?.generated_images} />
      </Panel>

      <Panel title="Sensor statistics" subtitle="Descriptive statistics calculated in Python from the cleaned Parquet dataset.">
        <SensorStatisticsTable statistics={edaData?.sensor_statistics} />
      </Panel>

      <div className="two-column-grid">
        <Panel title="Data-quality profile" subtitle="Missing values by input and target column.">
          <DataQualityChart data={quality} />
        </Panel>
        <Panel title="IQR outlier analysis" subtitle="Potential outliers identified separately for each sensor using the 1.5 × IQR rule.">
          <OutlierAnalysisChart data={edaData?.outlier_analysis} />
        </Panel>
      </div>

      <div className="two-column-grid">
        <Panel title="Target-class balance" subtitle="Positive and negative records for the four common labels.">
          <TargetBalanceChart data={edaData?.target_balance} />
        </Panel>
        <Panel title="Rare-event visibility" subtitle="Positive rates on a logarithmic scale so swarming, absconding, and harvesting remain visible beside brood-health labels.">
          <TargetPositiveRateChart data={edaData?.target_balance} />
        </Panel>
      </div>

      <div className="two-column-grid">
        <Panel title="Hive data coverage" subtitle="Compare record counts, estimated coverage percentage, and observed duration for all hive streams.">
          <HiveCoverageChart data={edaData?.hive_stats} />
        </Panel>
        <Panel title="Positive labels by hive" subtitle="Identify which hives contain the event evidence available to each research module.">
          <TargetByHiveChart data={edaData?.target_by_hive} />
        </Panel>
      </div>

      <div className="two-column-grid">
        <Panel title="Interactive sensor distribution" subtitle="Histogram bins generated by the Python backend from the complete cleaned dataset.">
          <SensorDistributionChart data={edaData?.sensor_histograms} />
        </Panel>
        <Panel title="Sensor correlation heatmap" subtitle="Pearson correlation among the four common sensor measurements.">
          <CorrelationHeatmap data={edaData?.correlation} />
        </Panel>
      </div>

      <div className="three-column-grid">
        <Panel title="Hourly patterns" subtitle="Average diurnal behaviour across all hives.">
          <HourlyPatternsChart data={edaData?.hourly_patterns} />
        </Panel>
        <Panel title="Weekday patterns" subtitle="Average variation across the seven days of the week.">
          <WeekdayPatternsChart data={edaData?.weekday_patterns} />
        </Panel>
        <Panel title="Monthly patterns" subtitle="Long-term changes across the full dataset period.">
          <MonthlyPatternsChart data={edaData?.monthly_patterns} />
        </Panel>
      </div>

      <div className="two-column-grid">
        <Panel title="Monthly target timeline" subtitle="Explore each target as an absolute count or a rate per 10,000 monthly observations.">
          <TargetTimelineChart data={edaData?.monthly_target_counts} />
        </Panel>
        <Panel title="Target-label co-occurrence" subtitle="Shows whether multiple labels are positive in the same record.">
          <TargetCooccurrenceHeatmap data={edaData?.target_cooccurrence} />
        </Panel>
      </div>

      <div className="two-column-grid">
        <Panel title="Target-conditioned sensor differences" subtitle="Standardized difference between positive-label and negative-label sensor means.">
          <TargetSensorEffectChart data={edaData?.target_sensor_effects} />
        </Panel>
        <Panel title="Sensor relationship explorer" subtitle="Compare any two sensors using a deterministic sample returned by the backend.">
          <SensorRelationshipChart data={edaData?.relationship_sample} />
        </Panel>
      </div>
    </div>
  );
}
